Functioning connection failure detection. Will not run tests and repe…
wmaop/wm-jbehave pull request #15
Opened 2018-04-25 18:03 UTC by Geraden07

…atedly attempt to connect if initial connection test fails.

2018-04-25 19:17 UTC, Geraden07 commented
Callback to Issue #13 .

2018-05-17 14:56 UTC, sysgen requested changes
Changes ok however assertion failure message is too 'in the code' and should contain something that is understandable to the runner of the test (eg a non java dev, just a wM user) such as a message suggesting to check the host, port and credentials.

2018-05-17 22:52 UTC, Geraden07 commented
Hmm, interesting. I see what you're saying.

Here's the thing. In the event of an authentication failure, the message shown will actually be the 
```Unable to connect to <host> : <port> with user <username> - <exception message>"``` which comes from the ExecutionContext class connectToServer method. This AssertionError is thrown and bubbles up without being caught so that's what the user sees.

The other two messages I have coded are:
1. ``` Assert.fail("In testing connection to the server, isConnected came back false");```

This should never happen. Either testConnection returns true or throws the AssertionError with the "unable to connect...." message mentioned above.

I'm not a fan of having a testConnection method return void, just out of principle I suppose, but that might make things cleaner.

Or I could change it to an IllegalStateException instead of an Assertion fail, as I think it's more of a technical failure case. In that situation, the more "in the code" message is a little more appropriate. Do you agree?


2. ```fail("Execution Context is null");```

Again this is the type of thing that should never happen as the execution context is initialized when you get the reference to the thread context (which is how you're calling this in the first place). So perhaps an exception is more appropriate.

I am a fan of catching/preventing NPE's, stating WHAT is null, and (re)throwing as an NPE for greater traceability because I've spent many an hour hunting nulls. So I've changed this to do exactly that. The alternative would be to simply get rid of the null check and ```return executionContext.testConnection()``` without the check.

2018-06-01 07:52 UTC, sysgen approved these changes

2018-06-01 07:54 UTC, merged